config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'search/search'
  root :to => "homes#top"
  get "home/about" => "homes#about"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
  # resources :relationships, only: [:create, :destroy]
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/search', to: 'searchs#search'



end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
          <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
        <% else %>
          <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
          <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
          <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in'%></li>
        <% end %>
      </ul>
    </nav>
  </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class='body'>
      <div class='container'>
        <% if user_signed_in? %>
          <!--<div class="search-form">-->
          <div class="search">
          <%= form_with url: search_path, method: :get, local: true do |f| %>
          <%= f.text_field :content %>
          <%= f.select :model, options_for_select({ "User" => "user", "Book" => "book" }) %>
          <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
          <%= f.submit '検索' %>
          <% end %>

        <% end %>
        <p id="notice"><%= notice %></p>

        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>